# Config file version is used internally to detect non backward compatible breaks
# All times are in seconds, distances in blocks
# Strings can use &0..&f color coding
Courier:
  UseFees: false
  Version: 0.9.11
  Fee:
    Send: 10
  Route:
    InitialWait: 10
    NextRoute: 60
  Privacy:
    SealedEnvelope: false
  Postman:
    QuickDespawn: 3
    Despawn: 20
    SpawnDistance: 10
    BreakSpawnProtection: true
    Greeting: '&7Courier: &fA Postman has arrived with your mail!'
    MailDrop: '&7Courier: &fYour mail was dropped onto the ground.'
    Inventory: '&7Courier: &fYou had your hands full, the Postman put the mail in your inventory for you.'
    CannotDeliver: '&7Courier: &fA Postman has mail for you but was not allowed in this place.'
  Letter:
    Drop: '&7Courier: &fYour inventory is full, the letter was dropped onto the ground.'
    Inventory: '&7Courier: &fYou had your hands full, the letter can be found in your inventory.'
