name: Courier
main: se.troed.plugin.Courier.Courier
version: 0.0.1
author: defxor
commands:
  postman:
    description: Spawns a postman
    permission: courier.postman
    usage: /postman
  courier:
    description: Sends a message
    permission: courier.send
    usage: /courier playername message
permissions:
  courier.send:
    description: Sends a message
    default: false
  courier.postman:
    description: Spawns a postman
    default: op
