name: Courier
main: se.troed.plugin.Courier.Courier
version: 0.9.11
author: defxor
description: Item based Player to Player realistically rendered mail
website: http://dev.bukkit.org/server-mods/courier/
softdepend: [Vault]
commands:
  postman:
    description: Spawns a postman
    aliases: [mailman, postie]
    permission: courier.postman
    usage: /postman
  courier:
    description: Displays help information
    permission: courier.info
    usage: /courier
  post:
    description: Sends the letter currently held in hand to someone
    aliases: [mail, send]
    permission: courier.send
    usage: /post playername
  letter:
    description: Creates a letter
    aliases: [note, write]
    permission: courier.write
    usage: /letter message        # Can be repeated to add additional text to existing handheld letter
permissions:
  courier.send:
    description: Sends a message
    default: op
  courier.write:
    description: Creates a letter
    default: op
  courier.postman:
    description: Spawns a postman
    default: op
  courier.list:
    description: Allows players to use lazy name matching (suggestion list if more than one match)
    default: op
  courier.info:
    description: Lists Courier information
    default: true
  courier.theonepercent:
    description: No postage fees apply even if UseFees is set to true
    default: false