name: Courier
main: se.troed.plugin.Courier.Courier
version: 0.9.2
author: defxor
commands:
  postman:
    description: Spawns a postman
    permission: courier.postman
    usage: /postman
  courier:
    description: Deprecated
    permission: courier.send
    usage: /courier playername message
  post:
    description: Sends a letter
    permission: courier.send
    usage: /post playername message
permissions:
  courier.send:
    description: Sends a message
    default: false
  courier.postman:
    description: Spawns a postman
    default: op
  courier.list:
    description: Allows players to use lazy name matching (suggestion list if more than one match)
    default: op
