name: Courier
main: se.troed.plugin.Courier.Courier
version: 0.9.6
author: defxor
softdepend: [Vault]
commands:
  postman:
    description: Spawns a postman
    permission: courier.postman
    usage: /postman
  courier:
    description: Displays help information
    permission: courier.info
    usage: /courier
  post:
    description: Sends a letter
    permission: courier.send
    usage: /post playername message
permissions:
  courier.send:
    description: Sends a message
    default: op
  courier.postman:
    description: Spawns a postman
    default: op
  courier.list:
    description: Allows players to use lazy name matching (suggestion list if more than one match)
    default: op
  courier.info:
    description: Lists Courier information
    default: true
  courier.theonepercent:
    description: No postage fees apply even if UseFees is set to true
    default: false